### ISSUE TITLE
another problem with multibyte tags

### ISSUE THREAD

**Issue by nir0** [mbleigh/acts-as-taggable-on#464]
gem version is 3.0.1
error: Tag cannot be empty

```
2.0.0p195 :001 > post = NewsPost.new(id: 277423, 
2.0.0p195 :002 >           name: "В торговом центре 52-летний мужчина в туалете свел счеты с жизнью", 
2.0.0p195 :003 >           markdown: "В Тюмени проводится проверка по факту обнаружения в одном из торговых центров тела мужчины. Как сообщили \"Вслух.ру\" в пресс-службе регионального управления СК РФ, накануне, 19 января, около 21.30 в закрытой туалетной кабине на первом этаже в одном из торговых центров Тюмени обнаружено тело 52-летнего мужчины, покончившего жизнь самоубийством - воткнувшего нож себе в грудь. Проводится доследственная проверка.
2.0.0p195 :004"> 
2.0.0p195 :005"> Установлено, что дверь кабины была заперта изнутри. О случившемся сообщили посетители торгового центра, которые в тот момент находились в этом же помещении и услышали странный хрип. Следствие проводит комплекс необходимых мероприятий, направленных на установление всех обстоятельств произошедшего. Опрашиваются очевидцы и родственники погибшего. По результатам проверки будет принято решение.", 
2.0.0p195 :006 >           text: "<p>В Тюмени проводится проверка по&#160;факту обнаружения в&#160;одном из&#160;торговых центров тела мужчины. Как&#160;сообщили &#171;Вслух.ру&#187; в&#160;<span class=\"nobr\">пресс-службе</span> регионального управления СК&#160;РФ, накануне, 19&#160;января, около 21.30 в&#160;закрытой туалетной кабине на&#160;первом этаже в&#160;одном из&#160;торговых центров Тюмени обнаружено тело <span class=\"nobr\">52-летнего</span> мужчины, покончившего жизнь самоубийством &#8211; воткнувшего нож&#160;себе в&#160;грудь. Проводится доследственная проверка.</p>
2.0.0p195 :007"> 
2.0.0p195 :008"> <p>Установлено, что&#160;дверь кабины была заперта изнутри. О&#160;случившемся сообщили посетители торгового центра, которые в&#160;тот момент находились в&#160;этом же&#160;помещении и&#160;услышали странный хрип. Следствие проводит комплекс необходимых мероприятий, направленных на&#160;установление всех обстоятельств произошедшего. Опрашиваются очевидцы и&#160;родственники погибшего. По&#160;результатам проверки будет принято решение.</p>", 
2.0.0p195 :009 >           creator_id: 467, 
2.0.0p195 :010 >           rubric_id: 31, 
2.0.0p195 :011 >           genre: "lenta", 
2.0.0p195 :012 >           published_at: "2014-01-20 18:38:00 +0600", 
2.0.0p195 :013 >           annotation: "Накануне, 19 января, около 21.30 в закрытой туалетной кабине на первом этаже в одном из торговых центров Тюмени обнаружено тело мужчины 1961 года рождения, покончившего жизнь самоубийством.", 
2.0.0p195 :014 >           source: "Вслух.ру", 
2.0.0p195 :015 >           source_url: "http://www.vsluh.ru", 
2.0.0p195 :016 >           author_name: "",
2.0.0p195 :017 >           author_email: "",
2.0.0p195 :018 >           tag_list: "СК РФ, следствие, проверка, самоубийство, суицид",
2.0.0p195 :019 >           exclude_from_rss: false,
2.0.0p195 :020 >           main_in_rubric_from: "",
2.0.0p195 :021 >           commentable: true,
2.0.0p195 :022 >           views_count: 90,
2.0.0p195 :023 >           created_at: "2014-01-20 18:36:14 +0600",
2.0.0p195 :024 >           updated_at: "2014-01-20 20:23:31 +0600",
2.0.0p195 :025 >           creator_id: 467,
2.0.0p195 :026 >           updater_id: 467,
2.0.0p195 :027 >           visibility: true,
2.0.0p195 :028 >           author_id: false,
2.0.0p195 :029 >           hide_banner: false,
2.0.0p195 :030 >           redirect_url: "",
2.0.0p195 :031 >           likes_count: 0,
2.0.0p195 :032 >           shares_count: 0,
2.0.0p195 :033 >           rating: 0
2.0.0p195 :034?>         )
 => #<NewsPost id: 277423, rubric_id: 31, name: "В торговом центре 52-летний мужчина в туалете свел ...", genre: "lenta", published_at: "2014-01-20 12:38:00", annotation: "Накануне, 19 января, около 21.30 в закрытой туалетн...", text: "<p>В Тюмени проводится проверка по&#160;факту обнар...", exclude_from_rss: false, main_in_rubric_from: nil, main_on_site_from: nil, views_count: 90, creator_id: 467, updater_id: 467, locker_id: nil, visibility: true, type: "NewsPost", author_id: 0, markdown: "В Тюмени проводится проверка по факту обнаружения в...", likes_count: 0, shares_count: 0, rating: 0, storage: {"source"=>"Вслух.ру", "source_url"=>"http://www.vsluh.ru", "author_name"=>"", "author_email"=>"", "redirect_url"=>""}, created_at: "2014-01-20 12:36:14", updated_at: "2014-01-20 14:23:31", hide_banner: false, commentable: true, delta: true, published_messages_count: 0> 
2.0.0p195 :035 > post.save!(validate: false)
   (0.4ms)  BEGIN
  SQL (103.2ms)  INSERT INTO "posts" ("annotation", "commentable", "created_at", "creator_id", "genre", "hide_banner", "id", "likes_count", "markdown", "name", "published_at", "rubric_id", "shares_count", "storage", "text", "type", "updated_at", "updater_id", "views_count", "visibility") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) RETURNING "id"  [["annotation", "Накануне, 19 января, около 21.30 в закрытой туалетной кабине на первом этаже в одном из торговых центров Тюмени обнаружено тело мужчины 1961 года рождения, покончившего жизнь самоубийством."], ["commentable", true], ["created_at", Mon, 20 Jan 2014 18:36:14 YEKT +06:00], ["creator_id", 467], ["genre", "lenta"], ["hide_banner", false], ["id", 277423], ["likes_count", 0], ["markdown", "В Тюмени проводится проверка по факту обнаружения в одном из торговых центров тела мужчины. Как сообщили \"Вслух.ру\" в пресс-службе регионального управления СК РФ, накануне, 19 января, около 21.30 в закрытой туалетной кабине на первом этаже в одном из торговых центров Тюмени обнаружено тело 52-летнего мужчины, покончившего жизнь самоубийством - воткнувшего нож себе в грудь. Проводится доследственная проверка.\n\nУстановлено, что дверь кабины была заперта изнутри. О случившемся сообщили посетители торгового центра, которые в тот момент находились в этом же помещении и услышали странный хрип. Следствие проводит комплекс необходимых мероприятий, направленных на установление всех обстоятельств произошедшего. Опрашиваются очевидцы и родственники погибшего. По результатам проверки будет принято решение."], ["name", "В торговом центре 52-летний мужчина в туалете свел счеты с жизнью"], ["published_at", Mon, 20 Jan 2014 18:38:00 YEKT +06:00], ["rubric_id", 31], ["shares_count", 0], ["storage", "{\"source\":\"Вслух.ру\",\"source_url\":\"http://www.vsluh.ru\",\"author_name\":\"\",\"author_email\":\"\",\"redirect_url\":\"\"}"], ["text", "<p>В Тюмени проводится проверка по&#160;факту обнаружения в&#160;одном из&#160;торговых центров тела мужчины. Как&#160;сообщили &#171;Вслух.ру&#187; в&#160;<span class=\"nobr\">пресс-службе</span> регионального управления СК&#160;РФ, накануне, 19&#160;января, около 21.30 в&#160;закрытой туалетной кабине на&#160;первом этаже в&#160;одном из&#160;торговых центров Тюмени обнаружено тело <span class=\"nobr\">52-летнего</span> мужчины, покончившего жизнь самоубийством &#8211; воткнувшего нож&#160;себе в&#160;грудь. Проводится доследственная проверка.</p>\n\n<p>Установлено, что&#160;дверь кабины была заперта изнутри. О&#160;случившемся сообщили посетители торгового центра, которые в&#160;тот момент находились в&#160;этом же&#160;помещении и&#160;услышали странный хрип. Следствие проводит комплекс необходимых мероприятий, направленных на&#160;установление всех обстоятельств произошедшего. Опрашиваются очевидцы и&#160;родственники погибшего. По&#160;результатам проверки будет принято решение.</p>"], ["type", "NewsPost"], ["updated_at", Mon, 20 Jan 2014 20:23:31 YEKT +06:00], ["updater_id", 467], ["views_count", 90], ["visibility", true]]
  ActsAsTaggableOn::Tag Load (1.8ms)  SELECT "tags".* FROM "tags" WHERE (lower(name) = 'СК РФ' OR lower(name) = 'следствие' OR lower(name) = 'проверка' OR lower(name) = 'самоубийство' OR lower(name) = 'суицид')
  ActsAsTaggableOn::Tag Exists (6.6ms)  SELECT 1 AS one FROM "tags" WHERE "tags"."name" = 'СК РФ' LIMIT 1
  ActsAsTaggableOn::Tag Exists (1.1ms)  SELECT 1 AS one FROM "tags" WHERE "tags"."name" = 'проверка' LIMIT 1
  SQL (35.9ms)  INSERT INTO "tags" ("name") VALUES ($1) RETURNING "id"  [["name", "проверка"]]
  ActsAsTaggableOn::Tag Exists (0.6ms)  SELECT 1 AS one FROM "tags" WHERE "tags"."name" = 'самоубийство' LIMIT 1
  SQL (0.6ms)  INSERT INTO "tags" ("name") VALUES ($1) RETURNING "id"  [["name", "самоубийство"]]
  ActsAsTaggableOn::Tag Exists (0.6ms)  SELECT 1 AS one FROM "tags" WHERE "tags"."name" = 'суицид' LIMIT 1
  SQL (0.6ms)  INSERT INTO "tags" ("name") VALUES ($1) RETURNING "id"  [["name", "суицид"]]
  ActsAsTaggableOn::Tag Load (2.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2 AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)  [["taggable_id", 277423], ["taggable_type", "Post"]]
  ActsAsTaggableOn::Tagging Exists (16.5ms)  SELECT 1 AS one FROM "taggings" WHERE ("taggings"."tag_id" IS NULL AND "taggings"."taggable_type" = 'Post' AND "taggings"."taggable_id" = 277423 AND "taggings"."context" = 'tags' AND "taggings"."tagger_id" IS NULL AND "taggings"."tagger_type" IS NULL) LIMIT 1
   (0.3ms)  ROLLBACK
ActiveRecord::RecordInvalid: Возникли ошибки: Tag не может быть пустым
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:37:in `insert_record'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:463:in `block (2 levels) in create_record'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:367:in `add_to_target'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:461:in `block in create_record'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:152:in `block in transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:151:in `transaction'
... 12 levels...
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
    from (irb):35
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /home/nir0/.rvm/gems/ruby-2.0.0-p195@vsluh4dev/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'2.0.0p195 :036 >
```

**Comment by HeshamAmiri** [comment]
Same here
acts-as-taggable-on (3.4.3)
activerecord (4.2.0)
pg (0.18.1)

**Comment by bf4** [comment]
Prs welcome.  I don't think any of the maintainers use it anymore.

B mobile phone

On Jan 17, 2015, at 11:39 AM, Hesham Amiri <notifications@github.com> wrote:

Same here
acts-as-taggable-on (3.4.3)
activerecord (4.2.0)
pg (0.18.1)

—
Reply to this email directly or view it on GitHub
<https://github.com/mbleigh/acts-as-taggable-on/issues/464#issuecomment-70375933>
.

**Comment by sintro** [comment]
Looks like the problem is still here. Thanks to using SQL statements with "lower()" commands, it is highly possible that the gem will not work fine in PostgreSQL (and I just didn`t check others). As I can understand, there are still problems in Postgres with stirng functions like lower() or upper() with multibyte characters when the database created without specifying the needed language (like ru_RU.UTF-8). I created the database by rake db:create, and the encoding is set to unicode in databases.yml, but it created with default "C" locale. And for this locale lower() and upper() functions   not works.

**Comment by chip-and-dail** [comment]
problem is still here...

mb_chars not helped :(

**Comment by Yakubiv** [comment]
You can fix it by adding this to the initializer:

```
ActsAsTaggableOn.force_lowercase = true
```

It is not perfect, but at least if fixed my issue with act as taggable and Cyrillic.

**Comment by seuros** [comment]
Believed fixed on current versions. If you can still reproduce it on v13, open a fresh issue and we will take a look.
