### ISSUE TITLE
N+1 Query Failed for  "undefined method `preloaded_records' for :tag:Symbol"

### ISSUE THREAD

**Issue by hadwinzhy** [mbleigh/acts-as-taggable-on#605]
env:
1. acts-as-taggable-on (3.4.2)
2. rails (4.1.5)

problem:
I have a "Recruitment" class which has "acts_as_taggable"

``` ruby
class Recruitment < ActiveRecord::Base
    acts_as_taggable
    ...
end
```

when i run the code `jobs = Recruitment.where(xxxx)`

it shows N+1 query detected:

``` console
 Recruitment Load (1.6ms)  SELECT `recruitments`.* FROM `recruitments`  WHERE `recruitments`.`product_id` = 36592
  ActsAsTaggableOn::Tag Load (1.8ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 112 AND `taggings`.`taggable_type` = 'Recruitment' AND `taggings`.`context` = 'tags'
  ActsAsTaggableOn::Tag Load (1.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 113 AND `taggings`.`taggable_type` = 'Recruitment' AND `taggings`.`context` = 'tags'
N+1 Query detected
 Recruitment => [:tags]
 Add to your finder: :include => [:tags]
N+1 Query method call stack
  /local/code/company/gurudigger/gurudigger/gurudigger_git4/app/controllers/api/helpers.rb:21:in `block in represent_each'
```

so I add includes method for query: `jobs = Recruitment.where(xxxx).includes([:tags])`

it show error below:

``` console
NoMethodError - undefined method `preloaded_records' for :tag:Symbol:
  activerecord (4.1.5) lib/active_record/associations/preloader/through_association.rb:32:in `associated_records_by_owner'
  activerecord (4.1.5) lib/active_record/associations/preloader/has_many_through.rb:8:in `associated_records_by_owner'
  activerecord (4.1.5) lib/active_record/associations/preloader/collection_association.rb:13:in `preload'
  activerecord (4.1.5) lib/active_record/associations/preloader/association.rb:20:in `run'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:137:in `block (2 levels) in preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:135:in `block in preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:134:in `preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:106:in `preloaders_on'
  bullet (4.14.0) lib/bullet/active_record41.rb:35:in `preloaders_on'
  squeel (1.2.1) lib/squeel/adapters/active_record/4.1/preloader_extensions.rb:21:in `block in preload_with_squeel'
  squeel (1.2.1) lib/squeel/adapters/active_record/4.1/preloader_extensions.rb:20:in `preload_with_squeel'
  activerecord (4.1.5) lib/active_record/relation.rb:610:in `block in exec_queries'
  activerecord (4.1.5) lib/active_record/relation.rb:609:in `exec_queries'
  activerecord (4.1.5) lib/active_record/relation.rb:486:in `load'
  activerecord (4.1.5) lib/active_record/relation.rb:231:in `to_a'
  bullet (4.14.0) lib/bullet/active_record41.rb:10:in `to_a'
  activerecord (4.1.5) lib/active_record/relation/delegation.rb:46:in `map'
  app/controllers/api/helpers.rb:21:in `represent_each'

```

I lost here, so can anybody help me? thx

**Comment by jamespolanco** [comment]
I had a similar error using Chewy for ElasticSearch import in 4.1.9. I was able to solve the `Symbol` error by adding `references` to the `includes`, so for your example:

```ruby
jobs = Recruitment.where(xxxx).includes(:tags).references(:tags)
```

I don't know if this will solve your issue, but I wanted to throw it out there just incase.

**Comment by seuros** [comment]
This applies to Rails and Ruby versions the gem no longer supports. Current baseline is Rails 8 and Ruby 3.3, so closing.
