### ISSUE TITLE
getting ArgumentError error after upgrading

### ISSUE THREAD

**Issue by ruba-ruba** [mbleigh/acts-as-taggable-on#624]
Ruby 2.1.2
Rails 4.1.6
Acts-as-taggable-on 3.4.2

i've already execute ```rake acts_as_taggable_on_engine:install:migrations``` an run a migrations

i have next code
```Ruby
class Post < ActiveRecord::Base
  acts_as_taggable_on :skills
...
```

```SQL
pry(main)> Post.first.skill_list
Post Load (0.2ms)  SELECT  `posts`.* FROM `posts`   ORDER BY `posts`.`id` ASC LIMIT 1
ArgumentError: You tried to define an association named tag on the model ActsAsTaggableOn::Tagging, but this will conflict with a method tag already defined by Active Record. Please choose a different association name.
from /home/user/.rvm/gems/ruby-2.1.2@blog/gems/activerecord-4.1.6/lib/active_record/associations/builder/association.rb:30:in `build'
```

```SQL
[1] pry(main)> Post.first.skills
  Post Load (0.1ms)  SELECT  `posts`.* FROM `posts`   ORDER BY `posts`.`id` ASC LIMIT 1
ArgumentError: You tried to define an association named tag on the model ActsAsTaggableOn::Tagging, but this will conflict with a method tag already defined by Active Record. Please choose a different association name.
from /home/user/.rvm/gems/ruby-2.1.2@blog/gems/activerecord-4.1.6/lib/active_record/associations/builder/association.rb:30:in `build'
```

```SQL
[3] pry(main)> Post.first.skill_list.add("coding")
  Post Load (0.3ms)  SELECT  `posts`.* FROM `posts`   ORDER BY `posts`.`id` ASC LIMIT 1
ArgumentError: You tried to define an association named tag on the model ActsAsTaggableOn::Tagging, but this will conflict with a method tag already defined by Active Record. Please choose a different association name.
from /home/user/.rvm/gems/ruby-2.1.2@blog/gems/activerecord-4.1.6/lib/active_record/associations/builder/association.rb:30:in `build'

```

**Comment by seuros** [comment]
Can your provide a sample app ?

**Comment by ruba-ruba** [comment]
@seuros yeah
this is my sample app [https://github.com/ruba-ruba/blog/tree/developing_gem] (https://github.com/ruba-ruba/blog/tree/developing_gem)
could you please try it on ```developing_gem``` branch
it shouldn't be difficult to install, migrate and try
thanks in advance

**Comment by yasu** [comment]
I get exactly same error in following environment:
Ruby 2.2.2
Rails 4.2.1
Acts-as-taggable-on 3.5.0

**Comment by seuros** [comment]
The stack this was reported on is long out of support, closing. If something similar shows up on Rails 8, please open a new issue.
