### ISSUE TITLE
tag_list returns RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by bastianwegge** [mbleigh/acts-as-taggable-on#636]
Pretty easy scenario, I've added the `gem 'acts_as_taggable_on'` to my Gemfile.

Wrote the following spec:

```
describe "POST #create" do
  let(:valid_attributes) { { title: "Neuer PCS Titel", tag_list: "these, are, tags" } }
  describe "with valid params" do
    it "holds the tags provided by valid params" do
      post :create, project: valid_attributes
      expect(Project.last.tags).to eq(valid_attributes[:tag_list])
    end
  end
end
```

Now I'm trying to implement the code to make this work:

```
def create
  @project = Project.new(project_params)
  @project.owner = current_user
  @project.save
  respond_with(@project)
end

[ ... ]

def project_params
  params.require(:project).permit(:title, :tag_list)
end
```

But I'm always getting the following error:

```
1) ProjectsController when logged in POST #create with valid params holds the tags provided by valid params
     Failure/Error: post :create, project: valid_attributes
     RuntimeError:
       can't modify frozen ActiveSupport::HashWithIndifferentAccess
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/hash_with_indifferent_access.rb:97:in `[]='
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/hash_with_indifferent_access.rb:97:in `[]='
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/acts_as_taggable_on-3.0.0.rc2/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb:319:in `process_dirty_object'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/acts_as_taggable_on-3.0.0.rc2/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb:300:in `set_tag_list_on'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/acts_as_taggable_on-3.0.0.rc2/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb:48:in `tag_list='
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `public_send'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/core.rb:557:in `init_attributes'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/core.rb:280:in `initialize'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # ./app/controllers/projects_controller.rb:29:in `create'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:629:in `process'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in `process'
     # /Users/bastianwegge/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:511:in `post'
     # ./spec/controllers/projects_controller_spec.rb:125:in `block (5 levels) in <top (required)>'
```

I provided the full stack to clear the versions I'm using. 

I also already tried the following, but it didn't work out that well:
```
params.require(:project).permit(:title, :tag_list => [])
```

**Comment by bastianwegge** [comment]
Might already have found the clue: https://github.com/mbleigh/acts-as-taggable-on/issues/580

Maybe adjusting the readme and removing the `@user.tag_list = "awesome, slick, hefty"` and other examples using a straight string might clear things up so none gets that wrong.

**Comment by georgetmayorga** [comment]
@bastianwegge What was your solution? You say passing the array didn't work out that well and I can't make out any corrective steps in the other issue you linked to. Thanks!

**Comment by seuros** [comment]
just use latest version.

**Comment by bastianwegge** [comment]
@georgetmayorga have you found the solution?

```
params.require(:object).permit(:tag_list)

+

= f.input :tag_list, input_html: { value: @object.tag_list.join(", ") }
```

solved it for me.

**Comment by bolshakov** [comment]
@seuros I know, I'm bit late... But if you had wrote exact version with that fix it would be really helpful since upgrading gem from 3.3 to 5.0 (latest version) on legacy app is tricky (I have to upgrade ruby and rails before). 

As I found the latests version on Apr 3, 2015 was 4.0.0
