### ISSUE TITLE
NoMethodError: undefined method `add'  in Ruby 2.2.3/Rails 4.2.3

### ISSUE THREAD

**Issue by nathanpop** [mbleigh/acts-as-taggable-on#688]
Hello - your help on this would be much-appreciated  -- I've tried this many times and seem to get the same issue - I cannot add tags using e.g: taglist.add("a") or taglist.remove("a) or set tags using taglist = 'a' , etc

I am using Ruby 2.2.3 and Rails 4.2.3. My gemfile has:
```ruby
gem 'acts-as-taggable-on', '~> 3.4'
```
I've also tried
```ruby
gem 'acts-as-taggable-on', '~> 3.5'
```

In my model I have:
```ruby
class Space < ActiveRecord::Base
  acts_as_taggable_on :skills
```

from the rails console I can do the following:
```ruby
> s = Space.first
 => #<Space id: 1172, created_at: "2015-09-24 08:13:09", ...<many fields>... updated_at: "2015-09-24 08:13:09"> 

> s.skills
  ActsAsTaggableOn::Tag Load (2.0ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2 AND "taggings"."context" = $3  [["taggable_id", 1172], ["taggable_type", "Space"], ["context", "skills"]]
 => #<ActiveRecord::Associations::CollectionProxy []> 

s.skills.add("a")
NoMethodError: undefined method `add' for #<ActiveRecord::Associations::CollectionProxy []>
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:136:in `method_missing'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:99:in `method_missing'
	from (irb):3
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/n/code/pop/poprails/bin/rails:8:in `<top (required)>'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/n/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/n/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.3 :004
```

**Comment by nathanpop** [comment]
Ok, I'll close this -- I posted on StackOverflow and received an answer:
http://stackoverflow.com/questions/32903766/acts-as-taggable-on-nomethoderror-undefined-method-add/32904197#32904197
