### ISSUE TITLE
Rails 5.0.0.beta1 issue acts-as-taggable-on v 3.5.0 when starting app

### ISSUE THREAD

**Issue by lohqua** [mbleigh/acts-as-taggable-on#711]
class BookPage < ActiveRecord::Base
    ... 
    acts_as_taggable #exception raised on this line
    acts_as_taggable_on :page_category
```
/home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/core_ext/hash/keys.rb:79:in `block in assert_valid_keys': Unknown key: :order. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors (ArgumentError)
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/core_ext/hash/keys.rb:77:in `each_key'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/core_ext/hash/keys.rb:77:in `assert_valid_keys'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/associations/builder/association.rb:78:in `validate_options'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/associations/builder/association.rb:44:in `create_reflection'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/associations/builder/association.rb:29:in `build'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/associations.rb:1358:in `has_many'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/compatibility.rb:7:in `has_many_with_taggable_compatibility'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:26:in `block (2 levels) in initialize_acts_as_taggable_on_core'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:23:in `class_eval'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:23:in `block in initialize_acts_as_taggable_on_core'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:17:in `each'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:17:in `initialize_acts_as_taggable_on_core'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable/core.rb:11:in `included'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable.rb:94:in `include'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable.rb:94:in `taggable_on'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable.rb:40:in `acts_as_taggable_on'
	from /home/me/sdk/ruby/lib64/ruby/gems/2.3.0/gems/acts-as-taggable-on-3.5.0/lib/acts_as_taggable_on/taggable.rb:16:in `acts_as_taggable'
```

**Comment by contradictioned** [comment]
:+1:

**Comment by contradictioned** [comment]
The following removes the errors, but I am not sure if this does not introduce further bugs.

Remove the unsupported options in [marked code](https://github.com/mbleigh/acts-as-taggable-on/blob/master/lib/acts_as_taggable_on/taggable/core.rb#L23-L38) such that only the following remains:

            has_many_with_taggable_compatibility context_taggings, as: :taggable,
                                                 dependent: :destroy,
                                                 class_name: 'ActsAsTaggableOn::Tagging'

            has_many_with_taggable_compatibility context_tags, through: context_taggings,
                                                 source: :tag,
                                                 class_name: 'ActsAsTaggableOn::Tag'

But as far as I see tags cannot be stored since on saving the tagged model a transaction is rolled back.

Maybe this helps someone with more ideas of this gem to debug :)

**Comment by plentz** [comment]
+1

**Comment by dborovsky** [comment]
To fix this, create an acts_as_taggable_on.rb file in config/initializers and place there following code:

```
module ActsAsTaggableOn::Utils
  def self.active_record4?
    true
  end
end

```after a restart, this problem should be solved.

**Comment by seuros** [comment]
This should be resolved in recent releases, closing. A new issue with a repro on a supported stack is welcome if it still bites.
