### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "tags" does not exist

### ISSUE THREAD

**Issue by sveredyuk** [mbleigh/acts-as-taggable-on#795]
gem 'acts-as-taggable-on',  '~> 4.0'
rails 5.0.1
postgres 9.6.1

```== 20162812090710 AddTaggingsCounterCacheToTags: migrating ====================
-- add_column(:tags, :taggings_count, :integer, {:default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "tags" does not exist
: ALTER TABLE "tags" ADD "taggings_count" integer DEFAULT 0
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_column'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/svr/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.1/lib/active_record/migration.rb:815:in `say_with_time'
```

**Comment by FloHeinle** [comment]
I tried to reproduce your issue, but couldn't. Tried with postgres version 9.6.1-3
Do you have an example app which reproduces the error?

This error message looks like the first migration, which creates the 'tags' table didn't work es expected.
Could you check if the tags table actually was created? 
In rails console you can check with:
`ActiveRecord::Base.connection.table_exists? 'tags'`

Bests

**Comment by sveredyuk** [comment]
`ActiveRecord::Base.connection.table_exists? 'tags' #=> false`

**Comment by sveredyuk** [comment]
Seems issue was with my local schema ) Sorry for distrub

**Comment by FloHeinle** [comment]
Glad it was resloved
