### ISSUE TITLE
Rails 5.1: Index name 'index_taggings_on_tag_id' on table 'taggings' already exists

### ISSUE THREAD

**Issue by jonhue** [mbleigh/acts-as-taggable-on#817]
When running `rake acts_as_taggable_on_engine:install:migrations` in Rails 5.1.0.rc1:

```
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_taggings_on_tag_id' on table 'taggings' already exists
c:/Users/Jonas/apps/slooob/slooob/db/migrate/20170321204023_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb:23:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ArgumentError: Index name 'index_taggings_on_tag_id' on table 'taggings' already exists
c:/Users/Jonas/apps/slooob/slooob/db/migrate/20170321204023_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb:23:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jonhue** [comment]
It is an issue in the first migration.

```
# This migration comes from acts_as_taggable_on_engine (originally 1)
class ActsAsTaggableOnMigration < ActiveRecord::Migration[5.1]
  def self.up
    create_table :tags do |t|
      t.string :name
    end

    create_table :taggings do |t|
      t.references :tag

      # You should make sure that the column created is
      # long enough to store the required class names.
      t.references :taggable, polymorphic: true
      t.references :tagger, polymorphic: true

      # Limit is created to prevent MySQL error on index
      # length for MyISAM table type: http://bit.ly/vgW2Ql
      t.string :context, limit: 128

      t.datetime :created_at
    end

    ##### ISSUE ##### add_index :taggings, :tag_id ###### NOT WORKING IN MYSQL
    add_index :taggings, [:taggable_id, :taggable_type, :context]
  end

  def self.down
    drop_table :taggings
    drop_table :tags
  end
end

```

**Comment by syguer** [comment]
It looks caused by [this](https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L72)

Is index option true by default now? 😨

**Comment by jonhue** [comment]
Commit fixed the issue!

**Comment by syguer** [comment]
I think so.
But I cannot reproduce. So I think your DB is already applied migrations, isn't it?

**Comment by anoshko** [comment]
I have the same error

**Comment by trueinviso** [comment]
I had same issue, commit fixed it.  I also had to specify 5.1 in all the migrations.

**Comment by profsmallpine** [comment]
@trueinviso fancy to see you here 😀
